// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import AppShellController from "./app_shell_controller"
application.register("app-shell", AppShellController)

import StudentsController from "./students_controller"
application.register("students", StudentsController)

import TeachersController from "./teachers_controller"
application.register("teachers", TeachersController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import StudentPortalController from "./student_portal_controller"
application.register("student-portal", StudentPortalController)

import StudentCalendarController from "./student_calendar_controller"
application.register("student-calendar", StudentCalendarController)

import StudentHomeworkController from "./student_homework_controller"
application.register("student-homework", StudentHomeworkController)

import StudentMaterialsController from "./student_materials_controller"
application.register("student-materials", StudentMaterialsController)

import LessonsController from "./lessons_controller"
application.register("lessons", LessonsController)
