// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import AppShellController from "./app_shell_controller"
application.register("app-shell", AppShellController)

import StudentsController from "./students_controller"
application.register("students", StudentsController)

import TeachersController from "./teachers_controller"
application.register("teachers", TeachersController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import StudentPortalController from "./student_portal_controller"
application.register("student-portal", StudentPortalController)

import StudentCalendarController from "./student_calendar_controller"
application.register("student-calendar", StudentCalendarController)

import StudentHomeworkController from "./student_homework_controller"
application.register("student-homework", StudentHomeworkController)

import StudentMaterialsController from "./student_materials_controller"
application.register("student-materials", StudentMaterialsController)

import LessonsController from "./lessons_controller"
application.register("lessons", LessonsController)

import DashboardController from "./dashboard_controller"
application.register("dashboard", DashboardController)

import PaymentsController from "./payments_controller"
application.register("payments", PaymentsController)

import ProfileTabsController from "./profile_tabs_controller"
application.register("profile-tabs", ProfileTabsController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import LessonTypesController from "./lesson_types_controller"
application.register("lesson-types", LessonTypesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ProfileMenuController from "./profile_menu_controller"
application.register("profile-menu", ProfileMenuController)
