require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Exclude:
    - db/**/*
    - bin/*
    - config/deploy.rb
    - vendor/bundle/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - config/**/*
    - spec/**/*
    - lib/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Exclude:
    - config/**/*
    - config.ru
    - Rakefile

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*
    - config/**/*
    - config.ru
    - Rakefile

Style/RedundantFetchBlock:
  Exclude:
    - config/**/*

Style/GlobalStdStream:
  Exclude:
    - config/**/*

Style/SymbolArray:
  Exclude:
    - config/**/*

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/**/*

Layout/LineLength:
  Exclude:
    - config/**/*

Rails/FilePath:
  Exclude:
    - config/**/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/**/*
    - spec/**/*
    - app/services/**/*
    - lib/demo/**/*
    - app/controllers/teachers_controller.rb
    - app/controllers/students_controller.rb
    - app/models/teacher_profile.rb
    - app/models/student_profile.rb

Metrics/AbcSize:
  Exclude:
    - app/services/**/*
    - lib/demo/**/*
    - app/controllers/teachers_controller.rb
    - app/controllers/students_controller.rb
    - app/controllers/calendar_controller.rb
    - app/controllers/users/**/*
    - app/models/teacher_profile.rb
    - app/models/student_profile.rb

Metrics/ClassLength:
  Exclude:
    - app/services/**/*
    - lib/demo/**/*
    - app/controllers/teachers_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/services/**/*
    - lib/demo/**/*
    - app/controllers/teachers_controller.rb
    - app/controllers/calendar_controller.rb
    - app/models/student_profile.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/services/**/*
    - lib/demo/**/*
    - app/controllers/teachers_controller.rb

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/**/*

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10
